[package]
authors = ["Vivian Hellyer <vivian@hellyer.dev>"]
edition = "2018"
name = "leaves-models"
version = "0.1.0"

[dependencies]
serde = { default-features = false, features = ["derive", "std"], version = "^1.0.0" }
